[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "smix"
path = "./src/main.rs"

[dependencies]
anyhow = "1.0.100"
clap = { version = "4.5.48", features = ["derive"] }
image = { version = "0.25.8", features = ["png"] }
smix = { path = "../smix"}
